force-app/core/objects/ConnectedApp__mdt/ConnectedApp__mdt.object-meta.xml
<CustomObject>
    <label>Connected App</label>
    <pluralLabel>Connected Apps</pluralLabel>
</CustomObject>

force-app/core/objects/ConnectedApp__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>JSON representing Connected App Settings</description>
    <inlineHelpText>JSON representing Connected App Settings</inlineHelpText>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/core/classes/ConnectedAppSelector.cls
public with sharing class ConnectedAppSelector {
    public static List<ConnectedApp__mdt> fetchAll() {
        return [
            SELECT
                DeveloperName,
                Label,
                MasterLabel,
                NamespacePrefix,
                QualifiedApiName,
                SystemModStamp,
                Value__c
            FROM ConnectedApp__mdt
        ];
    }

    public static ConnectedApp__mdt fetchByName(String developerName) {
        return [
            SELECT
                DeveloperName,
                Label,
                MasterLabel,
                NamespacePrefix,
                QualifiedApiName,
                SystemModStamp,
                Value__c
            FROM ConnectedApp__mdt
            WHERE DeveloperName = :developerName
            LIMIT 1
        ];
    }
}